version: 2

exposures:
  # - name: Product Funnel Dashboard
  #   description: Models that are critical to our product funnel dashboard
  #   type: dashboard
  #   maturity: medium
  #   owner:
  #     name: ben
  #     email: ben@greenery.com
  #   depends_on:
  #     - ref('product_funnel')

  - name: User Moves
    description: This describes how the users are moving across the funnel
    type: dashboard
    maturity: medium
    owner:
      name: ben
      email: ben@greenery.com
    depends_on:
      - ref('user_movements')
